# -*- coding: utf-8 -*-
"""The curation record and its parts (WP-09).

Standard library plus :mod:`pgx.domain` only. Nothing here touches a database,
a filesystem or a network, and nothing here creates a persisted
:class:`pgx.domain.models.CuratedInterpretation`: WP-09 defines the contract
that stage must satisfy, and WP-10 owns the workflow that fills it in.

The shape of this module is one idea repeated. A source said something; a
curator concluded something; those are two objects, and no field belongs to
both. Every place the two could touch is a place a source's word could become
this project's claim, so each is spelled out and each is refused.
"""

from __future__ import annotations

import datetime as _dt
import re
from dataclasses import dataclass, field
from typing import Any, Dict, Mapping, Optional, Sequence, Tuple

from pgx.curation.errors import (CurationError, EvidenceSelectionError,
                                 RationaleError, RoleSeparationError,
                                 VocabularyError)
from pgx.curation.vocabulary import (Applicability, ConclusionState,
                                     ConflictState, CurationRole,
                                     EffectDimension, EvidenceRelationship,
                                     ExclusionReason, InterpretationStatus,
                                     REASSURING_TERMS, VOCABULARY_VERSION)
from pgx.domain.enums import Phenotype
from pgx.domain.hashing import canonical_json, ensure_utc, sha256_digest

__all__ = [
    "CURATION_RECORD_VERSION",
    "MINIMUM_RATIONALE_PART_LENGTH",
    "PLACEHOLDER_RATIONALE_PATTERNS",
    "PROHIBITED_CURATION_FIELDS",
    "RATIONALE_PARTS",
    "ConflictAnalysis",
    "CurationQuestion",
    "CurationRecordDraft",
    "EvidenceSelection",
    "InsufficiencyStatement",
    "Rationale",
    "ReviewSignature",
    "SourceReportedValues",
    "find_prohibited_curation_fields",
    "find_reassuring_language",
]

#: Bumped when the record's content shape changes.
CURATION_RECORD_VERSION = "pgx-curation-record/1"

#: Fields a curation record may never carry, whatever a caller intends. Three
#: groups, each for its own reason:
#:
#: * project conclusions inherited from the legacy seed, which WP-08 already
#:   refuses inside an evidence record and which must not reappear here;
#: * numeric scores of any kind, because a number invites arithmetic over
#:   judgement and produces a result nobody reviewed;
#: * executable rule and treatment fields, which belong to WP-11 and WP-14 and
#:   would make this record actionable before anyone approved it.
PROHIBITED_CURATION_FIELDS: Tuple[str, ...] = (
    # Legacy project conclusions. A superset of WP-08's
    # PROHIBITED_METADATA_FIELDS, checked by a test: a name WP-08 refuses
    # inside an evidence record must not become admissible one stage later,
    # where it would look like a reviewed conclusion rather than a leftover.
    "attention_level", "candidate_preference", "candidate_score",
    "demo_risk_level", "drug_behavior_hint", "effect_direction",
    "evidence_strength", "evidence_tier", "manual_drug_behavior",
    "manual_effect_direction", "manual_phenotypes", "manual_plain_language",
    "manual_risk_level", "manual_risk_meaning", "normalized_effect",
    "normalized_phenotype", "normalized_phenotype_group", "plain_language",
    "plain_language_mvp", "risk", "risk_level", "risk_meaning",
    "treatment_selection", "usable_for_mvp",
    # numeric judgement
    "confidence", "confidence_score", "certainty_score", "evidence_score",
    "quality_score", "safety_score", "severity_score", "strength_score",
    "weight", "rank", "priority_score",
    # executable / prescriptive
    "condition", "matcher_condition", "rule_condition", "when", "then",
    "dose", "dosage", "dose_adjustment", "recommendation",
    "recommended_action", "contraindication", "alternative_drug",
    "prescribe", "avoid",
)

#: A rationale part shorter than this is not an explanation. Deliberately
#: modest: the check that matters is the placeholder and circularity check
#: below, and a long enough placeholder should still be refused by those.
MINIMUM_RATIONALE_PART_LENGTH = 24

#: Rationales that say nothing, expressed as patterns rather than exact
#: strings so a reworded version of the same non-answer is still caught.
PLACEHOLDER_RATIONALE_PATTERNS: Tuple[str, ...] = (
    r"^\s*$",
    r"^\W*(n/?a|tbd|todo|fixme|xxx|\?+|-+|\.+)\W*$",
    r"\bcopied from (the )?legacy\b",
    r"\blegacy (says|said|value|hint)\b",
    r"\bmanual_effect_hints\b",
    r"\bas (per|in) (the )?(legacy|old|previous) (seed|csv|file|code)\b",
    r"\bthe score is (high|low|good)\b",
    r"\b(high|low) (clinpgx )?score\b",
    r"\bscore of \d",
    r"\bthe (ai|llm|model|assistant|claude|gpt) (selected|chose|decided|says|generated)\b",
    r"\bgenerated by (an? )?(ai|llm|model)\b",
    r"\bclinically known\b",
    r"\bwell[- ]known\b",
    r"\bobvious(ly)?\b",
    r"\bself[- ]evident\b",
    r"\bsee above\b",
    r"\bsame as (above|before)\b",
    r"\bno comment\b",
)

_PLACEHOLDER_RE = tuple(re.compile(pattern, re.IGNORECASE)
                        for pattern in PLACEHOLDER_RATIONALE_PATTERNS)

_WORD_RE = re.compile(r"[a-z0-9]+")


def find_prohibited_curation_fields(payload: Any,
                                    path: str = "") -> Tuple[str, ...]:
    """Every prohibited field name in ``payload``, as dotted paths.

    Recursive, because the obvious way to smuggle a risk level past a flat
    check is to nest it. Reports rather than deletes: a caller that wrote one
    needs to know which, and silently dropping it would hide the attempt.
    """
    found = []
    if isinstance(payload, Mapping):
        for key, value in payload.items():
            here = "%s.%s" % (path, key) if path else str(key)
            if str(key) in PROHIBITED_CURATION_FIELDS:
                found.append(here)
            found.extend(find_prohibited_curation_fields(value, here))
    elif isinstance(payload, (list, tuple)):
        for index, item in enumerate(payload):
            found.extend(find_prohibited_curation_fields(
                item, "%s[%d]" % (path, index)))
    return tuple(sorted(set(found)))


def find_reassuring_language(text: str) -> Tuple[str, ...]:
    """Reassuring phrases in ``text``.

    Used where a conclusion is ``INSUFFICIENT`` or ``CONFLICTING``. The
    vocabulary can be respected perfectly while the prose beside it says "so
    this is probably fine", and a reader takes away the prose.
    """
    lowered = " ".join((text or "").lower().split())
    return tuple(term for term in REASSURING_TERMS if term in lowered)


def _require_text(value: Any, name: str, minimum: int = 1) -> str:
    if not isinstance(value, str) or len(value.strip()) < minimum:
        raise CurationError(
            "%s must be text of at least %d characters" % (name, minimum))
    return value.strip()


def _significant_words(text: str) -> frozenset:
    return frozenset(_WORD_RE.findall((text or "").lower())) - frozenset({
        "the", "a", "an", "is", "are", "was", "were", "be", "been", "and",
        "or", "of", "to", "in", "on", "for", "with", "that", "this", "it",
        "as", "by", "at", "from", "which", "there", "not", "no",
    })


@dataclass(frozen=True)
class SourceReportedValues:
    """What the source itself reported, copied unchanged for comparison.

    Held in its own object so it can sit beside the curator's conclusion
    without ever being it. ClinPGx's ``significance.term == "yes"`` means what
    ClinPGx defined it to mean; it is not :class:`ConclusionState.SUPPORTED`,
    and ``score == 3.75`` is not confidence, importance or risk. A curator who
    concludes ``SUPPORTED`` here must say in the rationale how the evidence
    supports it - repeating the source's own flag is not that explanation.
    """

    evidence_record_uuid: str
    source_fields: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        _require_text(self.evidence_record_uuid, "evidence_record_uuid")
        if not isinstance(self.source_fields, Mapping):
            raise CurationError("source_fields must be a mapping")
        object.__setattr__(self, "source_fields",
                           dict(sorted(self.source_fields.items())))

    def to_json(self) -> Dict[str, Any]:
        return {
            "evidence_record_uuid": self.evidence_record_uuid,
            "source_fields": dict(self.source_fields),
            "note": ("Reported by the source. Not a curator conclusion and "
                     "not convertible into one without a rationale."),
        }


@dataclass(frozen=True)
class EvidenceSelection:
    """One evidence record, and why it is in or out of the conclusion.

    An exclusion keeps the record. Evidence that disappears when it disagrees
    makes the conclusion uncheckable, so ``EXCLUDED`` is a relationship the
    record carries rather than a deletion.
    """

    evidence_record_uuid: str
    natural_key: str
    relationship: EvidenceRelationship
    rationale: str
    source_version_status: str
    provider_source_key: str
    origin_source_key: Optional[str] = None
    origin_status: Optional[str] = None
    trace_verified: Optional[bool] = None
    fragment_ids: Tuple[str, ...] = ()
    publication_ids: Tuple[str, ...] = ()
    exclusion_reason: Optional[ExclusionReason] = None

    def __post_init__(self) -> None:
        _require_text(self.evidence_record_uuid, "evidence_record_uuid")
        _require_text(self.natural_key, "natural_key")
        if not isinstance(self.relationship, EvidenceRelationship):
            raise VocabularyError("relationship must be an EvidenceRelationship")
        _require_text(self.source_version_status, "source_version_status")
        _require_text(self.provider_source_key, "provider_source_key")
        object.__setattr__(self, "fragment_ids", tuple(self.fragment_ids))
        object.__setattr__(self, "publication_ids",
                           tuple(self.publication_ids))

        # An exclusion without a reason is a deletion with extra steps.
        if self.relationship is EvidenceRelationship.EXCLUDED:
            if not isinstance(self.exclusion_reason, ExclusionReason):
                raise EvidenceSelectionError(
                    "excluding %s requires an ExclusionReason; evidence that "
                    "leaves the record without one cannot be argued with"
                    % self.evidence_record_uuid)
        elif self.exclusion_reason is not None:
            raise EvidenceSelectionError(
                "%s carries an exclusion reason but relationship is %s"
                % (self.evidence_record_uuid, self.relationship))

        # Every selection is argued, included ones too: "why is this in" is as
        # much a scientific statement as "why is this out".
        rationale = _require_text(self.rationale, "rationale",
                                  MINIMUM_RATIONALE_PART_LENGTH)
        for pattern in _PLACEHOLDER_RE:
            if pattern.search(rationale):
                raise RationaleError(
                    "the rationale for %s is a placeholder: %r"
                    % (self.evidence_record_uuid, rationale),
                    rejected=(pattern.pattern,))
        object.__setattr__(self, "rationale", rationale)

    @property
    def is_included(self) -> bool:
        return self.relationship is not EvidenceRelationship.EXCLUDED

    def content_identity(self) -> Dict[str, Any]:
        return {
            "evidence_record_uuid": self.evidence_record_uuid,
            "natural_key": self.natural_key,
            "relationship": self.relationship.value,
            "rationale": self.rationale,
            "source_version_status": self.source_version_status,
            "provider_source_key": self.provider_source_key,
            "origin_source_key": self.origin_source_key,
            "origin_status": self.origin_status,
            "trace_verified": self.trace_verified,
            "fragment_ids": list(self.fragment_ids),
            "publication_ids": list(self.publication_ids),
            "exclusion_reason": (self.exclusion_reason.value
                                 if self.exclusion_reason else None),
        }

    def to_json(self) -> Dict[str, Any]:
        return self.content_identity()


@dataclass(frozen=True)
class CurationQuestion:
    """The exact question one curation record answers.

    Deliberately narrow. A conclusion recorded against a gene/drug pair alone
    would apply to every annotation sharing that pair, which is the legacy
    defect this protocol exists to stop: 3,084 rows were produced by
    pair-level overrides applied broadly. Scope that cannot be determined
    yields ``INSUFFICIENT`` or ``NOT_INTERPRETABLE``, never a broad default.
    """

    question_id: str
    gene_canonical_key: str
    drug_canonical_key: str
    effect_dimension: EffectDimension
    question_text: str
    phenotype_scope: Tuple[Phenotype, ...] = ()
    population_context: Optional[str] = None

    def __post_init__(self) -> None:
        _require_text(self.question_id, "question_id")
        _require_text(self.gene_canonical_key, "gene_canonical_key")
        _require_text(self.drug_canonical_key, "drug_canonical_key")
        _require_text(self.question_text, "question_text",
                      MINIMUM_RATIONALE_PART_LENGTH)
        if not isinstance(self.effect_dimension, EffectDimension):
            raise VocabularyError("effect_dimension must be an EffectDimension")
        for name, prefix in (("gene_canonical_key", "GENE:"),
                             ("drug_canonical_key", "DRUG:")):
            if not getattr(self, name).startswith(prefix):
                raise CurationError("%s must start with %r" % (name, prefix))
        scope = tuple(self.phenotype_scope)
        for item in scope:
            if not isinstance(item, Phenotype):
                raise VocabularyError(
                    "phenotype_scope holds Phenotype members; %r is not one"
                    % (item,))
        if len(set(scope)) != len(scope):
            raise CurationError("phenotype_scope must not repeat a phenotype")
        # Declaration order of the enum, so two questions over the same set
        # hash alike without the tuple implying a ranking.
        object.__setattr__(self, "phenotype_scope",
                           tuple(sorted(scope, key=lambda p: list(Phenotype).index(p))))

    def content_identity(self) -> Dict[str, Any]:
        return {
            "question_id": self.question_id,
            "gene_canonical_key": self.gene_canonical_key,
            "drug_canonical_key": self.drug_canonical_key,
            "effect_dimension": self.effect_dimension.value,
            "question_text": self.question_text,
            "phenotype_scope": [item.value for item in self.phenotype_scope],
            "population_context": self.population_context,
        }

    def to_json(self) -> Dict[str, Any]:
        return self.content_identity()


@dataclass(frozen=True)
class ConflictAnalysis:
    """What disagreed, and what that requires of a human.

    No precedence is expressible here. There is no field for a winning source,
    no ranking, and no merge: which statement prevails is a scientific decision
    about one specific disagreement, recorded as one. WP-05 took the same
    position for source conflicts and this is the same position one stage
    later.
    """

    state: ConflictState
    conflicting_evidence_uuids: Tuple[str, ...] = ()
    disputed_field: Optional[str] = None
    source_versions: Mapping[str, str] = field(default_factory=dict)
    applicability_differences: Optional[str] = None
    material: Optional[bool] = None
    curator_analysis: Optional[str] = None
    adjudication_required: bool = False

    def __post_init__(self) -> None:
        if not isinstance(self.state, ConflictState):
            raise VocabularyError("state must be a ConflictState")
        object.__setattr__(self, "conflicting_evidence_uuids",
                           tuple(self.conflicting_evidence_uuids))
        object.__setattr__(self, "source_versions",
                           dict(sorted(self.source_versions.items())))
        if self.state is ConflictState.NONE_IDENTIFIED:
            if self.conflicting_evidence_uuids:
                raise CurationError(
                    "NONE_IDENTIFIED names conflicting evidence; if evidence "
                    "conflicts, the state is PRESENT or UNRESOLVED")
            return
        # A conflict that names fewer than two records is not a conflict; it
        # is a note, and storing it as a conflict would inflate the count that
        # blocks rule construction.
        if len(set(self.conflicting_evidence_uuids)) < 2:
            raise CurationError(
                "a %s conflict names at least two evidence records; %d given"
                % (self.state.value, len(set(self.conflicting_evidence_uuids))))
        _require_text(self.disputed_field, "disputed_field")
        _require_text(self.curator_analysis, "curator_analysis",
                      MINIMUM_RATIONALE_PART_LENGTH)
        if self.material is None:
            raise CurationError(
                "a recorded conflict states whether it is material; "
                "'undetermined' is expressed by leaving the state UNRESOLVED "
                "with material=False and saying so in the analysis")

    @property
    def blocks_rule_construction(self) -> bool:
        """An unresolved material conflict is not rule-eligible.

        WP-11 builds rules; this property is what it must consult. Returning
        False here for a material disagreement nobody settled would let a rule
        be built over a question the science has not answered.
        """
        if self.state in (ConflictState.UNRESOLVED,
                          ConflictState.ADJUDICATION_REQUIRED):
            return True
        return bool(self.state is ConflictState.PRESENT and self.material)

    def content_identity(self) -> Dict[str, Any]:
        return {
            "state": self.state.value,
            "conflicting_evidence_uuids": list(self.conflicting_evidence_uuids),
            "disputed_field": self.disputed_field,
            "source_versions": dict(self.source_versions),
            "applicability_differences": self.applicability_differences,
            "material": self.material,
            "curator_analysis": self.curator_analysis,
            "adjudication_required": self.adjudication_required,
            "blocks_rule_construction": self.blocks_rule_construction,
        }

    def to_json(self) -> Dict[str, Any]:
        return self.content_identity()


@dataclass(frozen=True)
class InsufficiencyStatement:
    """Why no stronger conclusion is supported.

    Required whenever the conclusion is ``INSUFFICIENT``. Every field here
    exists so the answer reads as "we did not establish this", which is what
    it means - and never as "we established that there is nothing", which is
    the false reassurance ``SAFETY-INV-001`` forbids.
    """

    missing_information: str
    evidence_reviewed_uuids: Tuple[str, ...]
    why_no_stronger_conclusion: str
    unresolved_scope: str
    additional_evidence_required: bool
    adjudication_required: bool = False

    def __post_init__(self) -> None:
        for name in ("missing_information", "why_no_stronger_conclusion",
                     "unresolved_scope"):
            value = _require_text(getattr(self, name), name,
                                  MINIMUM_RATIONALE_PART_LENGTH)
            reassuring = find_reassuring_language(value)
            if reassuring:
                raise CurationError(
                    "%s reads as reassurance (%s). Insufficient evidence "
                    "means this project did not establish the answer, not "
                    "that the answer is benign." % (name, ", ".join(reassuring)))
            object.__setattr__(self, name, value)
        object.__setattr__(self, "evidence_reviewed_uuids",
                           tuple(self.evidence_reviewed_uuids))
        if not self.evidence_reviewed_uuids:
            raise EvidenceSelectionError(
                "an insufficient conclusion still states which evidence was "
                "reviewed; otherwise it cannot be distinguished from nobody "
                "having looked")

    def content_identity(self) -> Dict[str, Any]:
        return {
            "missing_information": self.missing_information,
            "evidence_reviewed_uuids": list(self.evidence_reviewed_uuids),
            "why_no_stronger_conclusion": self.why_no_stronger_conclusion,
            "unresolved_scope": self.unresolved_scope,
            "additional_evidence_required": self.additional_evidence_required,
            "adjudication_required": self.adjudication_required,
        }

    def to_json(self) -> Dict[str, Any]:
        return self.content_identity()


@dataclass(frozen=True)
class ReviewSignature:
    """One person, one role, one moment, one reason.

    ``role`` is checked against what the act requires, not merely recorded. An
    engineering observer may confirm the pipeline is sound; that is a
    different claim from the science being right, and this type will not let
    the first stand in for the second.
    """

    person: str
    role: CurationRole
    at: _dt.datetime
    rationale: str

    #: Names that look like a person and are not one. Treated as absence
    #: rather than as weak identity: 'TEST_REVIEWER' approving a scientific
    #: protocol is not a lesser approval, it is none.
    PLACEHOLDER_NAMES = (
        "test", "test_reviewer", "test reviewer", "todo", "tbd", "team",
        "the team", "scientific advisor", "advisor", "anonymous", "anon",
        "system", "automated", "auto", "n/a", "na", "none", "nobody",
        "reviewer", "curator", "admin", "user", "someone", "unknown",
        "ai", "llm", "claude", "gpt", "assistant", "model", "bot",
        "placeholder", "example", "sample", "dummy", "xxx",
    )

    def __post_init__(self) -> None:
        person = _require_text(self.person, "person", 2)
        if person.strip().lower() in self.PLACEHOLDER_NAMES:
            raise RoleSeparationError(
                "%r is a placeholder, not a person. A scientific decision "
                "records who made it, and a name nobody can be held to is "
                "the same as no name." % person)
        object.__setattr__(self, "person", person)
        if not isinstance(self.role, CurationRole):
            raise VocabularyError("role must be a CurationRole")
        object.__setattr__(self, "at", ensure_utc(self.at, "at"))
        object.__setattr__(
            self, "rationale",
            _require_text(self.rationale, "rationale",
                          MINIMUM_RATIONALE_PART_LENGTH))

    def content_identity(self) -> Dict[str, Any]:
        return {
            "person": self.person,
            "role": self.role.value,
            "at": self.at.isoformat().replace("+00:00", "Z"),
            "rationale": self.rationale,
        }

    def to_json(self) -> Dict[str, Any]:
        return self.content_identity()


#: The fourteen parts of a structured rationale, in the order the protocol
#: asks for them. Named as data so the field dictionary, the published schema
#: and the review checklist can all be generated from one list.
RATIONALE_PARTS: Tuple[Tuple[str, str], ...] = (
    ("curation_question", "The exact question being answered."),
    ("selected_evidence", "Which evidence was selected, and why each piece."),
    ("excluded_evidence", "Which evidence was excluded, and why each piece."),
    ("source_to_conclusion", "How the selected evidence supports the "
                             "conclusion. Repeating a source flag is not this."),
    ("phenotype_normalization", "How source phenotype wording became the "
                                "normalized scope, or why none applies."),
    ("effect_normalization", "How the source's described effect became the "
                             "recorded effect dimension."),
    ("significance_explanation", "What the source reported as significance, "
                                 "and how the curator's conclusion differs "
                                 "from or follows it."),
    ("applicability_statement", "The population and context this applies to."),
    ("conflict_assessment", "Whether the evidence disagrees, and what that "
                            "means for this conclusion."),
    ("uncertainty_and_limitations", "What is uncertain, and what that limits."),
    ("missing_data_statement", "What is absent, stated as absence."),
)


@dataclass(frozen=True)
class Rationale:
    """The structured explanation behind one conclusion.

    Structured rather than free text, because a single prose box invites the
    one-line non-answer this protocol exists to refuse. Each part is checked
    for placeholders, and the whole is checked for circularity: a rationale
    that only restates the conclusion has explained nothing.
    """

    parts: Mapping[str, str]
    protocol_version: str
    authored_by: ReviewSignature
    reviewed_by: Optional[ReviewSignature] = None

    def __post_init__(self) -> None:
        if not isinstance(self.parts, Mapping):
            raise RationaleError("parts must be a mapping")
        expected = tuple(name for name, _ in RATIONALE_PARTS)
        missing = [name for name in expected
                   if not (self.parts.get(name) or "").strip()]
        unknown = sorted(set(self.parts) - set(expected))
        if unknown:
            raise RationaleError(
                "unknown rationale part(s): %s" % ", ".join(unknown))
        if missing:
            raise RationaleError(
                "the rationale is missing %d of %d required parts: %s"
                % (len(missing), len(expected), ", ".join(missing)),
                missing=missing)

        rejected = []
        for name in expected:
            text = str(self.parts[name]).strip()
            if len(text) < MINIMUM_RATIONALE_PART_LENGTH:
                rejected.append("%s: shorter than %d characters"
                                % (name, MINIMUM_RATIONALE_PART_LENGTH))
                continue
            for pattern in _PLACEHOLDER_RE:
                if pattern.search(text):
                    rejected.append("%s: matches placeholder %r"
                                    % (name, pattern.pattern))
                    break
        if rejected:
            raise RationaleError(
                "the rationale contains placeholder text: %s"
                % "; ".join(rejected), rejected=rejected)

        object.__setattr__(self, "parts",
                           {name: str(self.parts[name]).strip()
                            for name in expected})
        _require_text(self.protocol_version, "protocol_version")
        if not isinstance(self.authored_by, ReviewSignature):
            raise RationaleError("authored_by must be a ReviewSignature")
        if self.reviewed_by is not None:
            if not isinstance(self.reviewed_by, ReviewSignature):
                raise RationaleError("reviewed_by must be a ReviewSignature")
            if self.reviewed_by.person.strip().lower() == \
                    self.authored_by.person.strip().lower():
                raise RoleSeparationError(
                    "the independent reviewer must not be the author (%r). "
                    "One person checking their own conclusion is not an "
                    "independent review." % self.authored_by.person)
            if self.reviewed_by.role not in (
                    CurationRole.INDEPENDENT_SCIENTIFIC_REVIEWER,
                    CurationRole.ADJUDICATOR):
                raise RoleSeparationError(
                    "%s cannot serve as the independent scientific reviewer"
                    % self.reviewed_by.role.value)

    def is_circular_against(self, conclusion_text: str) -> bool:
        """Whether the explanation merely restates the conclusion.

        Compared on significant words rather than by string equality, because
        a restatement with the word order changed is still a restatement. The
        part that must add something is ``source_to_conclusion``: that is
        where "how does the evidence get us here" is answered.
        """
        conclusion_words = _significant_words(conclusion_text)
        if not conclusion_words:
            return False
        explanation = _significant_words(self.parts["source_to_conclusion"])
        new_words = explanation - conclusion_words
        return len(new_words) < 4

    def content_identity(self) -> Dict[str, Any]:
        return {
            "parts": dict(self.parts),
            "protocol_version": self.protocol_version,
            "authored_by": self.authored_by.content_identity(),
            "reviewed_by": (self.reviewed_by.content_identity()
                            if self.reviewed_by else None),
        }

    def to_json(self) -> Dict[str, Any]:
        return self.content_identity()


@dataclass(frozen=True)
class CurationRecordDraft:
    """One curator's answer to one curation question.

    A *draft* in the strict sense: this object never becomes a persisted
    :class:`pgx.domain.models.CuratedInterpretation`. There is no ``to_domain``
    here and no constructor there that takes one, because the transition from
    a reviewed conclusion to a stored row is a workflow with authorization,
    and WP-10 owns it. What this type does is refuse to hold a conclusion that
    such a workflow could not legitimately accept.
    """

    record_id: str
    question: CurationQuestion
    status: InterpretationStatus
    conclusion_state: ConclusionState
    conclusion_text: str
    applicability: Applicability
    effect_dimension: EffectDimension
    evidence: Tuple[EvidenceSelection, ...]
    conflict: ConflictAnalysis
    protocol_version: str
    source_reported: Tuple[SourceReportedValues, ...] = ()
    normalized_phenotypes: Tuple[Phenotype, ...] = ()
    rationale: Optional[Rationale] = None
    insufficiency: Optional[InsufficiencyStatement] = None
    unresolved_references: Tuple[str, ...] = ()
    curation_record_version: str = CURATION_RECORD_VERSION
    vocabulary_version: str = VOCABULARY_VERSION

    def __post_init__(self) -> None:
        _require_text(self.record_id, "record_id")
        _require_text(self.protocol_version, "protocol_version")
        _require_text(self.conclusion_text, "conclusion_text",
                      MINIMUM_RATIONALE_PART_LENGTH)
        for name, kind in (("question", CurationQuestion),
                           ("conflict", ConflictAnalysis)):
            if not isinstance(getattr(self, name), kind):
                raise CurationError("%s must be a %s" % (name, kind.__name__))
        for name, kind in (("status", InterpretationStatus),
                           ("conclusion_state", ConclusionState),
                           ("applicability", Applicability),
                           ("effect_dimension", EffectDimension)):
            if not isinstance(getattr(self, name), kind):
                raise VocabularyError("%s must be a %s"
                                      % (name, kind.__name__))

        object.__setattr__(self, "evidence", tuple(self.evidence))
        object.__setattr__(self, "source_reported",
                           tuple(self.source_reported))
        object.__setattr__(self, "unresolved_references",
                           tuple(self.unresolved_references))
        phenotypes = tuple(self.normalized_phenotypes)
        for item in phenotypes:
            if not isinstance(item, Phenotype):
                raise VocabularyError(
                    "normalized_phenotypes holds Phenotype members; %r is not"
                    % (item,))
        if len(set(phenotypes)) != len(phenotypes):
            raise CurationError("normalized_phenotypes must not repeat")
        object.__setattr__(self, "normalized_phenotypes", phenotypes)

        # Every conclusion cites evidence. A conclusion with none has nothing
        # to interpret, which is the same invariant CuratedInterpretation
        # already enforces one stage later.
        if not self.evidence:
            raise EvidenceSelectionError(
                "a curation record cites at least one evidence record; a "
                "conclusion with no evidence is untraceable")
        uuids = [item.evidence_record_uuid for item in self.evidence]
        if len(set(uuids)) != len(uuids):
            raise EvidenceSelectionError(
                "an evidence record appears twice in one selection")
        if not any(item.is_included for item in self.evidence):
            raise EvidenceSelectionError(
                "every cited record is excluded, so nothing supports this "
                "conclusion. Excluding everything is a finding of "
                "INSUFFICIENT, recorded as one.")

        # Prohibited content, checked over the whole record rather than over a
        # named field: a risk level nested inside a source_fields blob is the
        # same claim as one at the top level.
        prohibited = find_prohibited_curation_fields(self._scan_payload())
        if prohibited:
            raise CurationError(
                "a curation record must not carry %s. Risk, confidence, dose "
                "and rule fields belong to later stages that have their own "
                "approval; carrying one here makes an unreviewed conclusion "
                "look actionable." % ", ".join(prohibited))

        self._check_conclusion_consistency()
        self._check_status_requirements()

    def _scan_payload(self) -> Dict[str, Any]:
        """Everything a caller supplied, for the prohibited-field scan.

        Source-reported values are included deliberately. Unlike an evidence
        record - where the source's own payload is sacrosanct and scanning it
        would delete the source's words - a curation record is this project's
        object throughout, and a legacy ``demo_risk_level`` copied into it
        would be this project asserting it again.
        """
        return {
            "question": self.question.content_identity(),
            "conclusion_text": self.conclusion_text,
            "source_reported": [item.to_json() for item in self.source_reported],
            "rationale": (self.rationale.content_identity()
                          if self.rationale else None),
            "insufficiency": (self.insufficiency.content_identity()
                              if self.insufficiency else None),
        }

    def _check_conclusion_consistency(self) -> None:
        state = self.conclusion_state

        if state is ConclusionState.INSUFFICIENT:
            if self.insufficiency is None:
                raise CurationError(
                    "an INSUFFICIENT conclusion states what is missing, what "
                    "was reviewed, and what remains unresolved")
            reassuring = find_reassuring_language(self.conclusion_text)
            if reassuring:
                raise CurationError(
                    "an INSUFFICIENT conclusion reads as reassurance (%s). "
                    "Insufficient means this project did not establish the "
                    "answer; it is not low risk, no risk, no effect, safe, "
                    "normal, or negative evidence."
                    % ", ".join(reassuring))
        elif self.insufficiency is not None:
            raise CurationError(
                "insufficiency is stated on an INSUFFICIENT conclusion; this "
                "one is %s" % state.value)

        if state is ConclusionState.CONFLICTING:
            if self.conflict.state is ConflictState.NONE_IDENTIFIED:
                raise CurationError(
                    "a CONFLICTING conclusion records the conflict it found")
            reassuring = find_reassuring_language(self.conclusion_text)
            if reassuring:
                raise CurationError(
                    "a CONFLICTING conclusion reads as reassurance (%s). "
                    "Sources disagreeing is not evidence of absence of risk "
                    "(SAFETY-INV-008)." % ", ".join(reassuring))

        # Contradicting evidence must survive as contradicting. A conclusion
        # of SUPPORTED over evidence marked CONTRADICTS is allowed - the
        # curator may have weighed it - but only if the conflict analysis says
        # something, so the disagreement is on the record either way.
        contradicting = [item for item in self.evidence
                         if item.relationship is EvidenceRelationship.CONTRADICTS]
        if contradicting and self.conflict.state is ConflictState.NONE_IDENTIFIED:
            raise CurationError(
                "%d cited record(s) contradict this conclusion while the "
                "conflict state is NONE_IDENTIFIED. Contradicting evidence is "
                "assessed, not dropped." % len(contradicting))

    def _check_status_requirements(self) -> None:
        if self.status is not InterpretationStatus.CURATED:
            return
        if self.rationale is None:
            raise RationaleError(
                "a CURATED conclusion requires a structured rationale")
        if self.rationale.reviewed_by is None:
            raise RoleSeparationError(
                "a CURATED conclusion requires a named independent reviewer "
                "distinct from the author")
        if self.rationale.is_circular_against(self.conclusion_text):
            raise RationaleError(
                "the rationale restates the conclusion without explaining how "
                "the evidence supports it; that is not an explanation",
                rejected=("source_to_conclusion: circular",))
        if self.conflict.blocks_rule_construction and \
                self.conclusion_state is ConclusionState.SUPPORTED:
            raise CurationError(
                "an unresolved material conflict cannot back a SUPPORTED "
                "conclusion; the reviewed answer is CONFLICTING until a named "
                "adjudicator resolves it")

    @property
    def is_rule_eligible(self) -> bool:
        """Whether WP-11 may build a rule from this record.

        Deliberately conservative and deliberately here rather than in WP-11:
        the stage that knows why a conclusion is unsettled is this one.
        """
        return bool(
            self.status is InterpretationStatus.CURATED
            and self.conclusion_state is ConclusionState.SUPPORTED
            and not self.conflict.blocks_rule_construction
            and self.insufficiency is None
            and not self.unresolved_references)

    def included_evidence_uuids(self) -> Tuple[str, ...]:
        return tuple(item.evidence_record_uuid for item in self.evidence
                     if item.is_included)

    def excluded_evidence_uuids(self) -> Tuple[str, ...]:
        return tuple(item.evidence_record_uuid for item in self.evidence
                     if not item.is_included)

    def content_identity(self) -> Dict[str, Any]:
        return {
            "curation_record_version": self.curation_record_version,
            "vocabulary_version": self.vocabulary_version,
            "protocol_version": self.protocol_version,
            "record_id": self.record_id,
            "question": self.question.content_identity(),
            "status": self.status.value,
            "conclusion_state": self.conclusion_state.value,
            "conclusion_text": self.conclusion_text,
            "applicability": self.applicability.value,
            "effect_dimension": self.effect_dimension.value,
            "normalized_phenotypes": [item.value
                                      for item in self.normalized_phenotypes],
            "evidence": [item.content_identity() for item in self.evidence],
            "source_reported": [item.to_json() for item in self.source_reported],
            "conflict": self.conflict.content_identity(),
            "insufficiency": (self.insufficiency.content_identity()
                              if self.insufficiency else None),
            "rationale": (self.rationale.content_identity()
                          if self.rationale else None),
            "unresolved_references": list(self.unresolved_references),
        }

    def content_hash(self) -> str:
        return sha256_digest(self.content_identity())

    def to_json(self) -> Dict[str, Any]:
        payload = self.content_identity()
        payload["content_hash"] = self.content_hash()
        payload["is_rule_eligible"] = self.is_rule_eligible
        payload["included_evidence_uuids"] = list(
            self.included_evidence_uuids())
        payload["excluded_evidence_uuids"] = list(
            self.excluded_evidence_uuids())
        payload["note"] = (
            "A curation record under a protocol that is not yet approved. It "
            "is not a CuratedInterpretation, it is not executable, and it "
            "carries no attention level, risk level or treatment advice.")
        return payload
