# -*- coding: utf-8 -*-
"""Synthetic acquisition runs, caches and source policies for the WP-06 tests.

Everything here is fabricated on purpose and obviously so. The bodies are short
JSON documents, the URLs point at ``.invalid``, and every approved policy names
``TEST_SCIENTIFIC_REVIEWER`` - the shouted synthetic identity WP-05 established
for exactly this situation, where a mechanism needs an approval to exercise and
no real source has one.

Nothing here reads ``config/scientific-sources.json``. A companion test asserts
that the real registry approves nothing, and these fixtures must not be
mistaken for it.
"""

from __future__ import annotations

import datetime as _dt
import json
from typing import Mapping, Optional, Sequence

from pgx.domain.enums import SourceRole
from pgx.domain.hashing import sha256_digest
from pgx.ingestion.common.cache import ResponseCache, sha256_bytes
from pgx.ingestion.common.manifest import build_acquisition_manifest
from pgx.ingestion.common.models import (
    AcquisitionRunId,
    CacheState,
    EndpointCompletion,
    EndpointOutcome,
    HttpResponse,
    PaginationState,
    ParseStatus,
    RetrievalAttempt,
    RetrievalRecord,
)
from pgx.scientific.models import (
    AcquisitionMode,
    ClaimCategory,
    EvidenceType,
    EvidenceVerificationStatus,
    ReuseDimension,
    ReuseMatrix,
    ReusePermission,
    ReviewDecision,
    ReviewRecord,
    SourceEvidenceReference,
    SourcePolicyRecord,
    SourcePolicyStatus,
)
from pgx.scientific.policy import SourcePolicyRegistry

NOW = _dt.datetime(2026, 8, 30, 12, 0, 0, tzinfo=_dt.timezone.utc)
LATER = _dt.datetime(2026, 8, 30, 12, 5, 0, tzinfo=_dt.timezone.utc)
SOURCE_KEY = "fixture-source"
TEST_SCIENTIFIC_REVIEWER = "TEST_SCIENTIFIC_REVIEWER"
FIXTURE_TERMS_URL = "https://fixture.invalid/terms"


def body(index: int) -> bytes:
    """Deterministic response bytes. Never regenerated by reserialising."""
    return json.dumps({"page": index, "items": ["a", "b"]},
                      ensure_ascii=False).encode("utf-8")


def request_key(seed: str) -> str:
    """A synthetic request key in the shape WP-04 produces."""
    return sha256_digest({"fixture-request": seed})


def store(cache: ResponseCache, key: str, data: bytes) -> str:
    """Put exactly these bytes in the cache and return their digest."""
    response = HttpResponse(status_code=200, body=data,
                            headers={"Content-Type": "application/json"},
                            final_url="https://fixture.invalid/v1/page")
    cache.store(key, response)
    return sha256_bytes(data)


def record(
    key: str,
    data: bytes,
    endpoint_id: str = "fixture_endpoint",
    page_number: int = 1,
    cache_state: CacheState = CacheState.MISS,
    attempts: int = 1,
    started_at: _dt.datetime = NOW,
) -> RetrievalRecord:
    """One successful retrieval record pointing at cached bytes."""
    return RetrievalRecord(
        request_key=key,
        endpoint_id=endpoint_id,
        method="GET",
        url="https://fixture.invalid/v1/page?cursor=abc",
        safe_query=(("cursor", "abc"), ("cursor", "def")),
        page_number=page_number,
        cursor=None,
        started_at=started_at,
        completed_at=started_at + _dt.timedelta(seconds=1),
        status_code=200,
        raw_sha256=sha256_bytes(data),
        byte_length=len(data),
        content_type="application/json",
        cache_state=cache_state,
        cache_blob_ref=sha256_bytes(data),
        parse_status=ParseStatus.OK,
        record_count=2,
        attempts=tuple(
            RetrievalAttempt(attempt_number=n + 1,
                             started_at=started_at + _dt.timedelta(seconds=n),
                             status_code=200)
            for n in range(max(1, attempts))))


def endpoint(
    records: Sequence[RetrievalRecord],
    endpoint_id: str = "fixture_endpoint",
    required: bool = True,
    outcome: EndpointOutcome = EndpointOutcome.COMPLETE,
    terminal: bool = True,
) -> EndpointCompletion:
    return EndpointCompletion(
        endpoint_id=endpoint_id,
        required=required,
        outcome=outcome,
        pagination=PaginationState(
            pages_fetched=len(records), records_seen=2 * len(records),
            terminal=terminal,
            termination_reason="empty page" if terminal else "page budget spent"),
        records=tuple(records),
        error_detail=None if outcome is EndpointOutcome.COMPLETE else "fixture failure")


def complete_run(cache_root: str, pages: int = 2, cache_state=CacheState.MISS):
    """A cache holding two response bodies, and the COMPLETE manifest over them.

    Returns ``(cache, manifest)``. The bytes are written into the cache first,
    so a snapshot build reads exactly what a real run would have left behind.
    """
    cache = ResponseCache(cache_root)
    records = []
    for index in range(1, pages + 1):
        data = body(index)
        key = request_key("page-%d" % index)
        store(cache, key, data)
        records.append(record(key, data, page_number=index,
                              cache_state=cache_state))
    manifest = build_acquisition_manifest(
        run_id=AcquisitionRunId("fixture-run-0001"),
        source_id=SOURCE_KEY,
        started_at=NOW,
        completed_at=LATER,
        endpoints=(endpoint(records),),
        cache_root=cache_root,
        cache_only=cache_state is CacheState.HIT)
    return cache, manifest


def run_with_optional_warning(cache_root: str):
    """A run whose required endpoint completed and whose optional one failed."""
    cache = ResponseCache(cache_root)
    data = body(1)
    key = request_key("page-1")
    store(cache, key, data)
    required = endpoint([record(key, data)], endpoint_id="required_endpoint")
    optional = EndpointCompletion(
        endpoint_id="optional_endpoint", required=False,
        outcome=EndpointOutcome.FAILED,
        pagination=PaginationState(0, 0, False, "request failed"),
        records=(), error_detail="fixture: optional endpoint unavailable")
    manifest = build_acquisition_manifest(
        run_id=AcquisitionRunId("fixture-run-0002"), source_id=SOURCE_KEY,
        started_at=NOW, completed_at=LATER,
        endpoints=(required, optional), cache_root=cache_root)
    return cache, manifest


def run_with_incomplete_required(cache_root: str):
    """A run whose required endpoint never reached terminal pagination."""
    cache = ResponseCache(cache_root)
    data = body(1)
    key = request_key("page-1")
    store(cache, key, data)
    manifest = build_acquisition_manifest(
        run_id=AcquisitionRunId("fixture-run-0003"), source_id=SOURCE_KEY,
        started_at=NOW, completed_at=LATER,
        endpoints=(endpoint([record(key, data)], terminal=False),),
        cache_root=cache_root)
    return cache, manifest


# ---------------------------------------------------------------------------
# Synthetic source policy
# ---------------------------------------------------------------------------


def approved_policy(
    source_key: str = SOURCE_KEY,
    permissions: Optional[Mapping[ReuseDimension, ReusePermission]] = None,
    acquisition_mode: AcquisitionMode = AcquisitionMode.OFFICIAL_API,
) -> SourcePolicyRegistry:
    """A registry approving one synthetic source. Never the real registry."""
    matrix = permissions or {d: ReusePermission.ALLOWED for d in ReuseDimension}
    record_ = SourcePolicyRecord(
        source_key=source_key,
        display_name="Fixture source (synthetic, not a real scientific source)",
        role=SourceRole.SUPPORTING_ANNOTATION,
        status=SourcePolicyStatus.APPROVED,
        acquisition_mode=acquisition_mode,
        version_policy="fixture: pinned by the test",
        citation_policy="fixture: cited as a fixture",
        license_identifier="FIXTURE-NOT-A-REAL-LICENCE",
        reuse=ReuseMatrix(matrix),
        permitted_claim_categories=(ClaimCategory.SUPPORTING_ANNOTATION,),
        evidence=(SourceEvidenceReference(
            evidence_type=EvidenceType.OFFICIAL_TERMS_PAGE,
            official_url=FIXTURE_TERMS_URL,
            retrieved_at=NOW,
            content_hash=sha256_digest({"fixture": "terms"}),
            summary="Synthetic fixture terms.",
            verification=EvidenceVerificationStatus.VERIFIED),),
        review=ReviewRecord(
            decision=ReviewDecision.APPROVE,
            reviewer_name=TEST_SCIENTIFIC_REVIEWER,
            reviewer_role="synthetic fixture reviewer",
            decided_at=NOW,
            evidence_urls=(FIXTURE_TERMS_URL,)))
    return SourcePolicyRegistry(records=(record_,))


def pending_policy(source_key: str = SOURCE_KEY) -> SourcePolicyRegistry:
    """A registry that registers the source and approves nothing."""
    return SourcePolicyRegistry(records=(SourcePolicyRecord(
        source_key=source_key,
        display_name="Fixture pending source (synthetic)",
        role=SourceRole.SUPPORTING_ANNOTATION),))
