# -*- coding: utf-8 -*-
"""Lockfile and distribution builds (WP-24).

Two operations, and a rule that governs both: **nothing here writes a result
it did not obtain.**

``uv.lock`` is generated by ``uv``, from ``pyproject.toml``, against a real
package index. It is never written by this module, never templated, never
approximated from installed versions, and never carried over from another
project. A lockfile that was not resolved is not a lockfile - it is a list of
versions that happen to be written down, and the one thing a lockfile is for
is being the versions a resolver agreed on.

The distribution build runs the declared PEP 517 backend twice, from two
separate clean staging directories, and compares the artifact hashes.
``SOURCE_DATE_EPOCH`` is pinned across both runs, because a zip archive
records mtimes and two builds a second apart otherwise differ in bytes while
being identical in content - which would report irreproducibility that is not
there and, worse, would train whoever reads the report to ignore it.

When the index is unreachable, or the backend is not importable, the result is
``BLOCKED`` with the reason. That is a truthful measurement of this host and
is not a failure of the software.
"""

from __future__ import annotations

import hashlib
import os
import shutil
import subprocess  # noqa: S404 - building this project is the point
import tempfile
from typing import Mapping, Optional, Sequence, Tuple

from pgx.deployment.vocabulary import ExecutionState, blocker

__all__ = [
    "LOCKFILE_NAME",
    "SOURCE_DATE_EPOCH",
    "build_distributions_twice",
    "lock_dependencies",
    "verify_lockfile",
]

LOCKFILE_NAME = "uv.lock"

#: A fixed, deliberately unremarkable instant used for both builds so that
#: archive metadata cannot make two identical builds look different. Chosen
#: rather than "now" precisely because "now" differs between the two runs.
SOURCE_DATE_EPOCH = "1735689600"  # 2025-01-01T00:00:00Z

#: What is copied into a clean staging directory for a build. Everything a
#: source distribution declares plus the metadata the backend reads. Nothing
#: else - a build that could see ``.venv`` or ``data/`` would produce a
#: different artifact depending on what happened to be lying around.
STAGED_FOR_BUILD: Tuple[str, ...] = (
    "pyproject.toml", "README.md", "alembic.ini",
    "pgx", "apps", "migrations", "config", "schemas",
)

_BUILD_TIMEOUT_SECONDS = 600


def _run(argv: Sequence[str], *, cwd: Optional[str] = None,
         env: Optional[Mapping[str, str]] = None,
         timeout: int = 120) -> Tuple[int, str]:
    try:
        completed = subprocess.run(  # noqa: S603 - fixed argv, no shell
            list(argv), cwd=cwd, capture_output=True, text=True,
            timeout=timeout, check=False,
            env=dict(os.environ, **dict(env or {})))
    except FileNotFoundError:
        return 127, "%s is not installed" % argv[0]
    except subprocess.TimeoutExpired:
        return 124, "timed out after %ds" % timeout
    output = ((completed.stdout or "") + (completed.stderr or "")).strip()
    return completed.returncode, output[-2000:]


def _sha256(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return "sha256:" + digest.hexdigest()


# ---------------------------------------------------------------------------
# Lockfile
# ---------------------------------------------------------------------------

def lock_dependencies(root: str = ".", *, runner=None) -> Mapping[str, object]:
    """Resolve ``pyproject.toml`` into ``uv.lock``. One attempt.

    One attempt on purpose. An index that refused once will refuse again, and
    a retry loop turns a clear BLOCKED into a slow one while producing the
    same answer.
    """
    run = runner or _run
    lock_path = os.path.join(root, LOCKFILE_NAME)
    if shutil.which("uv") is None:
        return _lock_result(
            ExecutionState.BLOCKED, root,
            blocker_code="DEPLOY_PACKAGE_INDEX_UNAVAILABLE",
            owner="the build environment",
            detail="uv is not installed, so no resolution can be attempted")
    code, output = run(["uv", "lock", "--project", root], timeout=300)
    if code != 0:
        return _lock_result(
            ExecutionState.BLOCKED, root,
            blocker_code="DEPLOY_PACKAGE_INDEX_UNAVAILABLE",
            owner="the build environment",
            detail=("uv lock exited %d; no lockfile was written. The file is "
                    "never hand-written or approximated: a set of versions "
                    "no resolver agreed on is not a lockfile. Output: %s"
                    % (code, output.splitlines()[-1] if output else "none")))
    if not os.path.isfile(lock_path):  # pragma: no cover - uv wrote nothing
        return _lock_result(
            ExecutionState.BLOCKED, root,
            blocker_code="DEPLOY_LOCKFILE_ABSENT",
            owner="the build environment",
            detail="uv reported success but wrote no lockfile")
    return _lock_result(ExecutionState.EXECUTED, root)


def verify_lockfile(root: str = ".", *, runner=None) -> Mapping[str, object]:
    """Frozen check: does the lockfile still match ``pyproject.toml``?

    ``uv lock --check`` exits non-zero when the two disagree. That is the
    check CI runs, and it is the one that catches a dependency added to
    ``pyproject.toml`` without relocking - which otherwise ships an image
    built from versions the lockfile does not describe.
    """
    run = runner or _run
    lock_path = os.path.join(root, LOCKFILE_NAME)
    if not os.path.isfile(lock_path):
        return _lock_result(
            ExecutionState.BLOCKED, root,
            blocker_code="DEPLOY_LOCKFILE_ABSENT",
            owner="the build environment",
            detail="no uv.lock exists, so there is nothing to verify")
    if shutil.which("uv") is None:
        return _lock_result(
            ExecutionState.BLOCKED, root,
            blocker_code="DEPLOY_LOCKFILE_UNVERIFIED",
            owner="the build environment",
            detail="uv is not installed, so the frozen check cannot run")
    code, output = run(["uv", "lock", "--check", "--project", root],
                       timeout=180)
    if code != 0:
        return _lock_result(
            ExecutionState.BLOCKED, root,
            blocker_code="DEPLOY_LOCKFILE_UNVERIFIED",
            owner="whoever changed pyproject.toml",
            detail=("uv lock --check exited %d: the lockfile does not match "
                    "pyproject.toml" % code))
    return _lock_result(ExecutionState.VERIFIED, root)


def _lock_result(state: ExecutionState, root: str, *,
                 blocker_code: Optional[str] = None,
                 owner: str = "", detail: str = "") -> Mapping[str, object]:
    lock_path = os.path.join(root, LOCKFILE_NAME)
    present = os.path.isfile(lock_path)
    return {
        "lockfile_name": LOCKFILE_NAME,
        "lockfile_present": present,
        "lockfile_sha256": _sha256(lock_path) if present else None,
        "state": state.value,
        "blockers": ([dict(blocker(blocker_code, owner=owner,
                                   detail=detail).to_json())]
                     if blocker_code else []),
        "note": (
            "uv.lock is produced by uv against a real index or it does not "
            "exist. It is never hand-written, never approximated from "
            "installed versions, and never copied from elsewhere."),
    }


# ---------------------------------------------------------------------------
# Distributions
# ---------------------------------------------------------------------------

def _stage(root: str, destination: str) -> None:
    """Copy the declared build inputs into a clean directory.

    Copied rather than built in place so that the two builds cannot share a
    ``build/`` directory, a ``.egg-info`` or a cached wheel - each of which
    would make the second build agree with the first for the wrong reason.
    """
    for name in STAGED_FOR_BUILD:
        source = os.path.join(root, name)
        target = os.path.join(destination, name)
        if os.path.isdir(source):
            shutil.copytree(
                source, target,
                ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
        elif os.path.isfile(source):
            shutil.copy2(source, target)


def _build_once(root: str, *, runner=None) -> Mapping[str, object]:
    run = runner or _run
    staging = tempfile.mkdtemp(prefix="pgx-wp24-build-")
    try:
        _stage(root, staging)
        output_dir = os.path.join(staging, "dist")
        code, text = run(
            [os.environ.get("PYTHON", "python3"), "-m", "build",
             "--outdir", output_dir, staging],
            cwd=staging,
            env={"SOURCE_DATE_EPOCH": SOURCE_DATE_EPOCH,
                 "PYTHONHASHSEED": "0"},
            timeout=_BUILD_TIMEOUT_SECONDS)
        if code != 0:
            return {"ok": False, "detail": text.splitlines()[-1] if text
                    else "build exited %d" % code}
        artifacts = {}
        for name in sorted(os.listdir(output_dir)):
            path = os.path.join(output_dir, name)
            if name.endswith(".whl"):
                artifacts["wheel"] = {"name": name, "sha256": _sha256(path)}
            elif name.endswith(".tar.gz"):
                artifacts["sdist"] = {"name": name, "sha256": _sha256(path)}
        return {"ok": True, "artifacts": artifacts}
    finally:
        shutil.rmtree(staging, ignore_errors=True)


def build_distributions_twice(root: str = ".", *,
                              runner=None) -> Mapping[str, object]:
    """Build a wheel and an sdist twice, and compare the hashes.

    The comparison is the measurement. Two hashes that agree are evidence the
    build is reproducible *on this host, at this moment* - it is not evidence
    that it is reproducible on a different platform, and this report does not
    say that it is.
    """
    import importlib.util

    missing = [name for name in ("hatchling", "build")
               if importlib.util.find_spec(name) is None]
    if missing:
        return {
            "state": ExecutionState.BLOCKED.value,
            "reproducible": None,
            "builds": [],
            "blockers": [dict(blocker(
                "DEPLOY_BUILD_BACKEND_UNAVAILABLE",
                owner="the build environment",
                detail=("%s not importable here, so no distribution can be "
                        "produced with the declared backend. Substituting a "
                        "different backend would build a different artifact "
                        "than any deployment installs."
                        % ", ".join(sorted(missing)))).to_json())],
            "source_date_epoch": SOURCE_DATE_EPOCH,
            "note": _BUILD_NOTE,
        }
    first = _build_once(root, runner=runner)
    if not first.get("ok"):
        return {"state": ExecutionState.NOT_EXECUTED.value,
                "reproducible": None, "builds": [first],
                "blockers": [], "source_date_epoch": SOURCE_DATE_EPOCH,
                "note": _BUILD_NOTE}
    second = _build_once(root, runner=runner)
    if not second.get("ok"):
        return {"state": ExecutionState.NOT_EXECUTED.value,
                "reproducible": None, "builds": [first, second],
                "blockers": [], "source_date_epoch": SOURCE_DATE_EPOCH,
                "note": _BUILD_NOTE}
    left = first["artifacts"]  # type: ignore[index]
    right = second["artifacts"]  # type: ignore[index]
    comparisons = {}
    for kind in ("wheel", "sdist"):
        comparisons[kind] = {
            "first": left.get(kind), "second": right.get(kind),
            "identical": (left.get(kind) or {}).get("sha256")
            == (right.get(kind) or {}).get("sha256")
            and left.get(kind) is not None,
        }
    reproducible = all(item["identical"] for item in comparisons.values())
    return {
        "state": (ExecutionState.VERIFIED.value if reproducible
                  else ExecutionState.EXECUTED.value),
        "reproducible": reproducible,
        "comparisons": comparisons,
        "builds": [first, second],
        "blockers": [],
        "source_date_epoch": SOURCE_DATE_EPOCH,
        "note": _BUILD_NOTE,
    }


_BUILD_NOTE = (
    "Two builds from two clean staging directories with SOURCE_DATE_EPOCH "
    "pinned. Agreement is evidence of reproducibility on this host at this "
    "moment; it is not evidence of reproducibility across platforms, and this "
    "document does not claim that.")
