# -*- coding: utf-8 -*-
"""Build provenance (WP-24).

A build's provenance answers one question: *what exactly was this made from?*
Normally the answer starts with a commit hash. This repository has no commits -
``git log`` reports an empty ``main`` and every path is untracked - so
``source_revision`` is ``null`` here, and inventing a value for it would be
the first lie in a document whose entire purpose is to be checkable.

What stands in for it is a **source-tree manifest hash**: a digest over the
relative path and content hash of every source file that goes into a build,
sorted, with a declared exclusion list. It is not a commit hash and is not
presented as one; it is a content identity, and two builds from the same tree
produce the same value while any edit anywhere changes it.

Every other field follows the same rule. ``image_digest`` is present only when
an image was actually built. ``ci_run_id`` is present only when a provider
actually ran. ``built_at`` is present only for a real run - a provenance
document generated by a test carries ``null`` there, so a fixture can never be
mistaken for a build that happened at a time.
"""

from __future__ import annotations

import hashlib
import json
import os
import platform
import subprocess  # noqa: S404 - reading a repository's own state
import sys
from typing import Mapping, Optional, Sequence, Tuple

from pgx.deployment.runtime_assets import build_runtime_asset_manifest

__all__ = [
    "BUILD_PROVENANCE_VERSION",
    "SOURCE_EXCLUDED_PREFIXES",
    "build_provenance",
    "source_revision",
    "source_tree_manifest",
]

BUILD_PROVENANCE_VERSION = "pgx-wp24-build-provenance/1"

#: What the source identity excludes, and why each one.
#:
#: Generated output, virtual environments, caches and the staging area are
#: excluded because they are not source; ``.git`` because it is history rather
#: than content. Test files are *included*: a change to a test changes what a
#: build was verified by, and a provenance that ignored tests would report the
#: same identity for a tree whose verification had been deleted.
SOURCE_EXCLUDED_PREFIXES: Tuple[str, ...] = (
    ".git/", ".venv/", ".venv-linux/", "_to_delete/", "data/_to_delete/",
    "build/", "node_modules/", ".pytest_cache/", ".ruff_cache/",
    ".mypy_cache/",
)

SOURCE_EXCLUDED_SUFFIXES: Tuple[str, ...] = (".pyc", ".pyo", ".DS_Store")

SOURCE_EXCLUDED_DIR_NAMES: Tuple[str, ...] = ("__pycache__",)


def _file_digest(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _included(relative: str) -> bool:
    if any(relative.startswith(prefix) for prefix in
           SOURCE_EXCLUDED_PREFIXES):
        return False
    if any(relative.endswith(suffix) for suffix in SOURCE_EXCLUDED_SUFFIXES):
        return False
    return os.path.basename(relative) not in SOURCE_EXCLUDED_SUFFIXES


def source_tree_manifest(root: str = ".") -> Mapping[str, object]:
    """A content identity for the whole source tree.

    Deterministic by construction: paths are relativised, normalised to
    forward slashes and sorted before hashing, so the digest does not depend
    on directory-walk order, on the platform's path separator, or on where the
    checkout lives.
    """
    root = os.path.abspath(root)
    entries = []
    for base, directories, files in os.walk(root):
        directories[:] = sorted(
            name for name in directories
            if name not in SOURCE_EXCLUDED_DIR_NAMES)
        for name in sorted(files):
            absolute = os.path.join(base, name)
            relative = os.path.relpath(absolute, root).replace(os.sep, "/")
            if not _included(relative):
                continue
            try:
                entries.append((relative, _file_digest(absolute)))
            except OSError:  # pragma: no cover - a vanished file mid-walk
                continue
    entries.sort()
    payload = json.dumps(
        {"version": BUILD_PROVENANCE_VERSION, "files": entries},
        sort_keys=True, ensure_ascii=True, separators=(",", ":"))
    return {
        "file_count": len(entries),
        "manifest_hash": "sha256:" + hashlib.sha256(
            payload.encode("utf-8")).hexdigest(),
        "excluded_prefixes": list(SOURCE_EXCLUDED_PREFIXES),
        "excluded_suffixes": list(SOURCE_EXCLUDED_SUFFIXES),
        "note": (
            "A content identity, not a commit hash. Two checkouts with the "
            "same files produce the same value; it says nothing about "
            "history, authorship or review."),
    }


def source_revision(root: str = ".") -> Optional[str]:
    """The commit this tree is at, or ``None``.

    ``None`` is the honest answer for a repository with no commits, and it is
    returned rather than a placeholder string so that a consumer comparing
    provenance documents cannot match two builds on the word "unknown".
    """
    try:
        completed = subprocess.run(  # noqa: S603 - fixed argv, no shell
            ["git", "-C", root, "rev-parse", "HEAD"],
            capture_output=True, text=True, timeout=10, check=False)
    except (OSError, subprocess.SubprocessError):
        return None
    if completed.returncode != 0:
        return None
    value = (completed.stdout or "").strip()
    return value or None


def _hash_file(root: str, relative: str) -> Optional[str]:
    path = os.path.join(root, relative)
    if not os.path.isfile(path):
        return None
    return "sha256:" + _file_digest(path)


def build_provenance(root: str = ".", *,
                     image_repository: Optional[str] = None,
                     image_tag: Optional[str] = None,
                     image_digest: Optional[str] = None,
                     base_image: Optional[str] = None,
                     base_image_digest: Optional[str] = None,
                     wheel_hash: Optional[str] = None,
                     sdist_hash: Optional[str] = None,
                     sbom_hash: Optional[str] = None,
                     sbom_reference: Optional[str] = None,
                     built_at: Optional[str] = None,
                     ci_run_id: Optional[str] = None,
                     ci_run_url: Optional[str] = None,
                     builder: Optional[str] = None,
                     environ: Optional[Mapping[str, str]] = None
                     ) -> Mapping[str, object]:
    """Assemble the provenance document.

    Every optional argument defaults to ``None`` and is written as ``null``.
    That is the whole discipline: a field is present when the thing happened
    and null when it did not, so a reader can tell an unbuilt image from an
    image whose digest nobody recorded.
    """
    environ = dict(os.environ if environ is None else environ)
    manifest = source_tree_manifest(root)
    assets = build_runtime_asset_manifest(root)
    return {
        "build_provenance_version": BUILD_PROVENANCE_VERSION,
        "source_revision": source_revision(root),
        "source_revision_note": (
            "null when the repository has no commit. This repository has "
            "none: every path is untracked and `main` has no history, so the "
            "source-tree manifest hash below is the only content identity "
            "this build has."),
        "source_tree_manifest_hash": manifest["manifest_hash"],
        "source_tree_file_count": manifest["file_count"],
        "pyproject_hash": _hash_file(root, "pyproject.toml"),
        "lockfile_hash": _hash_file(root, "uv.lock"),
        "lockfile_present": os.path.isfile(os.path.join(root, "uv.lock")),
        "dockerfile_hash": _hash_file(root, "Dockerfile"),
        "python_version": platform.python_version(),
        "python_implementation": platform.python_implementation(),
        "platform_system": platform.system(),
        "platform_machine": platform.machine(),
        "builder": builder or ("python %s on %s" % (
            platform.python_version(), platform.system())),
        "builder_version": sys.version.split()[0],
        "wheel_sha256": wheel_hash,
        "sdist_sha256": sdist_hash,
        "image_repository": image_repository,
        "image_tag": image_tag,
        "image_digest": image_digest,
        "base_image": base_image,
        "base_image_digest": base_image_digest,
        "runtime_asset_manifest_hash": assets["manifest_hash"],
        "runtime_assets_satisfied": assets["satisfied"],
        "sbom_reference": sbom_reference,
        "sbom_sha256": sbom_hash,
        "built_at": built_at,
        "ci_run_id": ci_run_id or (environ.get("GITHUB_RUN_ID") or None),
        "ci_run_url": ci_run_url,
        "note": (
            "Every field describing something that did not happen is null, "
            "never zero and never a placeholder string. An absent image "
            "digest means no image was built; it does not mean an image was "
            "built and nobody wrote the digest down."),
    }


def compare_provenance(first: Mapping[str, object],
                       second: Mapping[str, object],
                       *, fields: Optional[Sequence[str]] = None
                       ) -> Mapping[str, object]:
    """Compare two provenance documents on the identity fields only.

    Timestamps, CI run ids and builder strings are excluded by default: two
    reproducible builds differ in all three and are still the same build. What
    must agree is what the build was made *from*.
    """
    identity = tuple(fields or (
        "source_tree_manifest_hash", "pyproject_hash", "lockfile_hash",
        "dockerfile_hash", "runtime_asset_manifest_hash",
        "wheel_sha256", "sdist_sha256"))
    differences = {name: [first.get(name), second.get(name)]
                   for name in identity
                   if first.get(name) != second.get(name)}
    return {
        "compared_fields": list(identity),
        "identical": not differences,
        "differences": differences,
        "excluded_fields": ["built_at", "ci_run_id", "ci_run_url", "builder",
                            "builder_version"],
        "note": (
            "Timestamps and runner identity are excluded on purpose: two "
            "reproducible builds differ in those and are the same build."),
    }
